<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[java.io.FileNotFoundException:  (The system cannot find the path specified)]]>
    </line>
    <line>
      <![CDATA[java.io.FileNotFoundException:  (The system cannot find the path specified)]]>
    </line>
  </reporter-output>
  <suite started-at="2020-07-20T11:10:49Z" name="Default suite" finished-at="2020-07-20T11:10:49Z" duration-ms="607">
    <groups>
    </groups>
    <test started-at="2020-07-20T11:10:49Z" name="Default test" finished-at="2020-07-20T11:10:49Z" duration-ms="607">
      <class name="testRunner.TestExecutionSuite">
        <test-method signature="executionSuite(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testRunner.TestExecutionSuite@5e63cad]" started-at="2020-07-20T11:10:49Z" name="executionSuite" finished-at="2020-07-20T11:10:49Z" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'ScenarioID' is required by @Test on method executionSuite but has not been marked @Optional or defined
in C:\Users\Nishant\AppData\Local\Temp\testng-eclipse--742275232\testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'ScenarioID' is required by @Test on method executionSuite but has not been marked @Optional or defined
in C:\Users\Nishant\AppData\Local\Temp\testng-eclipse--742275232\testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:290)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:359)
at org.testng.internal.Parameters.createParameters(Parameters.java:620)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executionSuite -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testRunner.TestExecutionSuite@5e63cad]" started-at="2020-07-20T11:10:49Z" name="tearDown" finished-at="2020-07-20T11:10:49Z" duration-ms="37" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[java.io.FileNotFoundException:  (The system cannot find the path specified)]]>
            </line>
            <line>
              <![CDATA[java.io.FileNotFoundException:  (The system cannot find the path specified)]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testRunner.TestExecutionSuite@5e63cad]" started-at="2020-07-20T11:10:49Z" name="afterSuite" finished-at="2020-07-20T11:10:51Z" duration-ms="1975" status="FAIL">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\LatestSheet.xlsx (A required privilege is not held by the client)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \LatestSheet.xlsx (A required privilege is not held by the client)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
at testRunner.TestExecutionSuite.afterSuite(TestExecutionSuite.java:192)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testRunner.TestExecutionSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
